# Site settings
baseurl = "http://blog.geeque.ru/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Geeque Blog"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-66101066-1"
hasCJKLanguage = true
publishDir = "Docs"
[params]
	name = "Grioriy Korzhuk"
	description = "About IT"
	bio = "Ghoul from DevOps"
	# Enter optionally your twitter account
	twitter = "633qu3"
	enableRSS = true

	# Disqus comment
	disqusShortname = "blog-zyirs7zgaa"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = true

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
        photos = '/photos'
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
  facebook-square = "https://www.facebook.com/profile.php?id=1102600595"
  twitter-square = "https://twitter.com/633qu3"
  github-square = "https://github.com/gkorzhuk"
